### ISSUE TITLE
Add a Contribution Guide

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/community.kubernetes#120]
##### SUMMARY

Add a Contribution Guide to the repo.

At a minimum, we should link to the [Ansible Community Guide](https://docs.ansible.com/ansible/latest/community/index.html). But ideally we'd have a [CONTRIBUTING.md](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md) file with more details.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docs

##### ADDITIONAL INFORMATION

N/A

**Comment by geerlingguy** [comment]
cc @gundalow @jillr - I was wondering do we have a template for community collections? Or should we just kind of modify one like the one that is linked above for our needs?

**Comment by jillr** [comment]
To the best of my knowledge we don't, I have an extremely [WIP](https://github.com/jillr/amazon.aws/blob/contrib_guide/CONTRIBUTING.md) draft  for the AWS collections.  I'm pulling a lot from the Community guide but supplementing it with data that's relevant specifically to the AWS community.  Feedback super welcome.

**Comment by gundalow** [comment]
My hope was https://github.com/ansible-collections/collection_template would become this.

**Comment by gundalow** [comment]
> ETA: I think it's extremely important we clearly note a CoC on each collection's contrib guide rather than just implicitly defer up to the Ansible CoC. If we do develop a template, that should be a part of it.

Yup, we haven't done that before (not something that I thought of), again would be good to add to the template repo.
