### ISSUE TITLE
Changelogs and breaking changes

### ISSUE THREAD

**Issue by abadger** [ansible-collections/community.kubernetes#124]
##### SUMMARY
Hi, I remember we talked and there was a thought that community.kubernetes was going to include backwards incompatible changes that hadn't gone through a deprecation cycle in ansible-2.9.x.

Is that the case still?  If so, I just wanted to make sure those changes get shown in a changelog entry (and porting guide if you have one).

I don't know if you're planning to use the antsibull-changelog tool that @felixfontein has been developing to manage your changelogs.  If you are, it has several change types which would end up in an automated, unified porting guide for ansible-2.10 if we can manage to get everything worked out on time.

i've cc'd him in case you want to discuss how that would work with him.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
Changelog.  Possibly Changelog.md

##### ANSIBLE VERSION
This is regarding ansible-2.10 and the community.kubernetes version that you're targeting for that.

**Comment by geerlingguy** [comment]
Closing this and moving changelog-specific discussion over to #40 — for now there are no breaking changes planned, and I'm thinking we'll do a 0.11.1 (or maybe call it a 1.0.0 at some point?) with some of the minor bugfixes/performance improvements we've added since early May.
