### ISSUE TITLE
helm action doesn't push changes to local charts

### ISSUE THREAD

**Issue by iameli** [ansible-collections/community.kubernetes#128]
##### SUMMARY
If you make changes to a chart that's defined in a local directory, Helm won't deploy those changes. It will only attempt to kick off a deploy if the `values` change, not the chart definition itself.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.kubernetes.helm

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /Users/iameli/code/livepeer-infra/ansible/ansible.cfg
  configured module search path = ['/Users/iameli/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.9/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.3 (default, Jun 10 2020, 15:04:14) [Clang 11.0.3 (clang-1103.0.32.29)]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/Users/iameli/code/livepeer-infra/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

macOS 10.15.3

##### STEPS TO REPRODUCE

1. Release a chart defined in a local directory
1. Make a change to any file within that chart (e.g. `example-chart/templates/example.yaml`)
1. Release the chart again

```yaml
- community.kubernetes.helm:
    chart_ref: "../charts/{{ livepeer_chart }}"
    release_name: "{{ livepeer_chart }}"
    kubeconfig_path: "../kubeconfigs/{{ inventory_hostname }}.secret"
    release_namespace: default
```

##### EXPECTED RESULTS
I'd expect the change to my local chart to be deployed to the cluster.

##### ACTUAL RESULTS

The module doesn't detect the change and nothing is released.

```paste below
TASK [helm : community.kubernetes.helm] *************************************************************************************
task path: /Users/iameli/code/livepeer-infra/ansible/roles/helm/tasks/main.yml:4
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: iameli
<localhost> EXEC /bin/sh -c 'echo ~iameli && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/iameli/.ansible/tmp `"&& mkdir /Users/iameli/.ansible/tmp/ansible-tmp-1591828498.385173-73690-91542488056012 && echo ansible-tmp-1591828498.385173-73690-91542488056012="` echo /Users/iameli/.ansible/tmp/ansible-tmp-1591828498.385173-73690-91542488056012 `" ) && sleep 0'
Using module file /Users/iameli/.ansible/collections/ansible_collections/community/kubernetes/plugins/modules/helm.py
<localhost> PUT /Users/iameli/.ansible/tmp/ansible-local-73651kglg9u3q/tmph1w1qml6 TO /Users/iameli/.ansible/tmp/ansible-tmp-1591828498.385173-73690-91542488056012/AnsiballZ_helm.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/iameli/.ansible/tmp/ansible-tmp-1591828498.385173-73690-91542488056012/ /Users/iameli/.ansible/tmp/ansible-tmp-1591828498.385173-73690-91542488056012/AnsiballZ_helm.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/local/bin/python3 /Users/iameli/.ansible/tmp/ansible-tmp-1591828498.385173-73690-91542488056012/AnsiballZ_helm.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/iameli/.ansible/tmp/ansible-tmp-1591828498.385173-73690-91542488056012/ > /dev/null 2>&1 && sleep 0'
ok: [rkv] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "binary_path": null,
            "chart_ref": "../charts/base",
            "chart_repo_url": null,
            "chart_version": null,
            "disable_hook": false,
            "force": false,
            "kube_context": null,
            "kubeconfig_path": "../kubeconfigs/rkv.secret",
            "purge": true,
            "release_name": "base",
            "release_namespace": "default",
            "release_state": "present",
            "release_values": {},
            "update_repo_cache": false,
            "wait": false,
            "wait_timeout": null
        }
    },
    "status": {
        "app_version": "1.16.0",
        "chart": "base-0.1.0",
        "name": "base",
        "namespace": "default",
        "revision": "3",
        "status": "deployed",
        "updated": "2020-06-09 23:13:39.119526 -0700 PDT",
        "values": {}
    }
}
```

**Comment by iameli** [comment]
Not totally sure how to work around this one other than using [helm-diff](https://github.com/databus23/helm-diff) to only kick off a deploy if there are changes.

**Comment by tima** [comment]
@LucasBoisserie and @Akasurde: Any thoughts on implementing this logic in the helm module?

**Comment by LucasBoisserie** [comment]
@iameli, you can use the parameter force to always trigger the upgrade or bump the version inside the Chart.yaml but this is not optimal

@tima
Helm-diff is a good suggestion. I didn't included it to limit external dependencies

But with helm-diff we could:
* implement ansible diff on chart like k8s module
* have a better management of idempotence


Currently idempotence is based of module input values and chart version, with helm diff we could use multiple values sources(#93) and make change inside chart

**Comment by choppedpork** [comment]
I believe I've hit a similar issue with the same underlying cause - I've created a helm chart which uses uses a `.Release.Time` based annotation when the container image tag is set to `latest` which combined with `pullPolicy: Always` allows for using `helm upgrade` to re-deploy an updated `latest` image quite neatly. We're been using this approach for a "bleeding-edge" test environment.

Similar as per the issue description, the changes do not get applied automatically via ansible because the values remain the same - and in my case so does the chart! - but the resulting manifests should be different. Using `force` did work until my chart evolved to use a service at which point I hit helm/helm#6378 😢

**Comment by tima** [comment]
We're going to fold addressing this and other related issues into #248.
