### ISSUE TITLE
How to debug locally a module = python file ?

### ISSUE THREAD

**Issue by cmoulliard** [ansible-collections/community.kubernetes#170]
### Problem

I try to debug using my IDE one of the AnsibleModule = python file (e.g. k8s_log.py) without success as I got a `ModuleNot found exception`

Example:
```
/Users/cmoullia/.venv/bin/python "/Users/cmoullia/Library/Application Support/JetBrains/IntelliJIdea2020.1/plugins/python/helpers/pydev/pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 50792 --file /Users/cmoullia/code/ansible/ansible_collections/community/kubernetes/plugins/modules/k8s_log.py
pydev debugger: process 76633 is connecting

Connected to pydev debugger (build 201.8538.31)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ModuleNotFoundError: No module named 'ansible_collections'

Process finished with exit code 1

OR

PYTHONPATH=.,/Users/cmoullia/code/ansible/ansible_collections python3 plugins/modules/k8s_log.py
Traceback (most recent call last):
  File "plugins/modules/k8s_log.py", line 131, in <module>
    from ansible_collections.community.kubernetes.plugins.module_utils.common import KubernetesAnsibleModule
ModuleNotFoundError: No module named 'ansible_collections'
```

What is then the workaround ?

**Comment by geerlingguy** [comment]
@cmoulliard have you tried asking about this in one of the #ansible IRC channels or in the Ansible Project mailing list? I haven't particularly tried debugging with an IDE with a collection, but this seems like something that would affect any collection and not just the kubernetes one.

Note that this collection depends on a working installation of Ansible to be able to run any of the modules, as the namespacing comes from Ansible and the collection must be in a path where Ansible can use the autoloader correctly.

**Comment by cmoulliard** [comment]
I tried on this channel without success - https://groups.google.com/g/ansible-project/c/SlDn22N-1zM. 

I agree with you that such a problem is not specific to k8s but should be addressed ideally by the ansible community.

**Comment by bmillemathias** [comment]
Debugging modules should be covered by https://docs.ansible.com/ansible/devel/dev_guide/debugging.html
There is a pending PR to update it due to recent changes https://github.com/ansible/ansible/pull/70847

Does it help ?

**Comment by Akasurde** [comment]
I will close this as this is not specific to k8s but overall Ansible specific. Thanks.
