### ISSUE TITLE
Proposal: Establish a separate collection for OpenShift (OKD) Content

### ISSUE THREAD

**Issue by tima** [ansible-collections/community.kubernetes#175]
# Proposal: Establish a separate collection for OpenShift (OKD) Content

*Author*: Timothy Appnel <@tima>

*Date*: 2020-08-03

- Status: New
- Proposal type: Content Split
- Targeted release: Fall 2020
- Estimated time to implement: TBD

## Motivation

The Ansible k8s content has been a collection of community contributed content for managing Kubernetes resources, applications and services. Through these contributions it has also inherited a bits of OpenShift (OKD) extensions not found in standard Kubernetes distributions.

Balancing the support of OKD users and the broader Kubernetes community has been manageable so far, it will just become more challenging to effective develop and test while serving both user communities as needs evolve and grow in sophistication. 

I am proposing that we migrate all OKD community extensions functions out of this collection and establish a separate Ansible Collection called community.okd that will be their new home.

### Problems

- Problem 1

OpenShift provides enhancements and additional functionality to the standard Kubernetes distribution and associated tools. Without extra care, these differences can lead to inconsistencies and confusion for user trying to automate their cloud native environments. As time goes on this will become a bigger challenge. 

- Problem 2

The Ansible `k8s_*` modules and other plugins use the [openshift-restclient-python dynamic API client](https://github.com/openshift/openshift-restclient-python). While this library covers both native K8s functionality in addition to OpenShift specific extensions effectively, the requirement of the library raises questions and concerns with the broader Kubernetes community to its compatibility with all distributions.

- Problem 3

OpenShift integration testing requires specialized environment and considerations that will weigh down the Kubernetes content development as a whole. Currently, automated testing of OKD functionality has not been automated and left to community verification. 

## Solution proposal

* Establish community.okd repository under ansible-collections
* Migrate OpenShift  specific code, issues and PRs to community.okd
* Deprecate any OpenShift specific functionality from this community.kubernetes.
* Replace the [openshift-restclient-python library](https://github.com/openshift/openshift-restclient-python) dependency with [the official python client library for Kubernetes](https://github.com/kubernetes-client/python) porting and refactoring code as needed to maintain the same functional behaviors. 

This proposed action will make it easier and more effectively to serve these two distinct though related user communities. Switching to the official Kubernetes client and the decoupling of all OpenShift code will assure compatibility for their respective objectives and enable independent decision making on the features, functionality and release cadence. 

## Dependencies (optional)

* https://github.com/kubernetes-client/python would become the primary dependency for all K8s API functionality in this collection.
* It would be very helpful to maintaining compatibility and correctness if the following PRs where merged and released:
  * https://github.com/kubernetes-client/python-base/pull/186
  * https://github.com/kubernetes-client/python-base/pull/187
  * https://github.com/kubernetes-client/python-base/pull/188

## Testing (optional)

Testing OpenShift functionality has additional and specialized requirements that goes beyond the CI testing used by this repo. This issue will be addressed as part of establishing the community.okd repository.

## Documentation (optional)

Documentation for any these changes and any porting would be documented. Further documentation on using community.kubernetes and community.okd together will likely be needed.

**Comment by geerlingguy** [comment]
I'd be happy with this change, as it would make two things a lot easier:

  1. Removing the remaining openshift 3.x test code from both ansible/ansible and this repository's `ansible-test integration` tests.
  2. Allowing the openshift collection to (hopefully?) integrate with OpenShift's ecosystem testing tools, so that collection's content could be tested against an actual OpenShift 4.x cluster.

**Comment by maxamillion** [comment]
:+1: shipit

**Comment by willthames** [comment]
I'm hugely negative on
> Replace the openshift-restclient-python library dependency with the official python client library for Kubernetes porting and refactoring code as needed to maintain the same functional behaviors.

I've spent a lot of effort putting kubernetes features that the ansible k8s modules depend upon into that module, there are a lot of great features in there. Just because of the name doesn't mean it's not a great python module for managing kubernetes, and this proposal ignores that legacy. 

I'm cool with the rest of it though, I don't like even having to see openshift issues lodged against the kubernetes collection

**Comment by willthames** [comment]
To be clear, the following features in the openshift-restclient-python library are heavily relied upon by the k8s modules:
* client-side apply
* diff
* append_hash
* transparent merge_type
* validate

Admittedly those cases all have excellent test coverage if you just wanted to reimplement them inside the collection, but also I'm not sure why you'd bother. There's also a super close collaboration between this project and the openshift-restclient-python project (@fabianvf is obviously heavily involved in both, and I'm perhaps less obviously heavily involved in both) which means that getting improvements in is pretty straightforward (only slightly less easy than just putting the improvements in the collection)

**Comment by tima** [comment]
@willthames: I appreciate your concern. We're not just going to pull one library out for the other and break things. We're looking at that carefully and are well aware of the technical challenges -- some that you've outlined in your comments which really helpful in identifying areas were the official Kubernetes client is lacking today. We've thought this over and feel taking this on is a worthwhile and vital endeavor we must take on. I'll leave the technical implementation details to @fabianvf, @geerlingguy, @akasurde and @maxamillion to work through here.

For me, the most significant consideration in making this move was embracing and supporting the broader Kubernetes community and most importantly, contribute what we can to improve the official python client library for all. 

Recently the Operator SDK made it into the CNCF as an incubator project. That donation includes the Ansible Operator SDK that will depend on the content in this collection. That has prompted additional feedback and concern that the Ansible Operator SDK content (this collection) is using an openshift library (regardless of its merits) and not using the official client library. I can appreciate where they are coming from and think they are valid concerns to consider.

I also think it will have the benefit of helping assure we don't let any "openshift-isms" creep into this k8s collection.

So our plan is to do this methodically and to not break things. We will also try to upstream everything we can into the official Kubernetes client repo for the benefit of the broader community. @fabianvf has already contributed somethings and we antiquate a lot more to come out of this exercise. We may have to carry some extra code around in this collection until we work through all of that, but that's open source for you. 

Hope that makes sense.

**Comment by geerlingguy** [comment]
@tima - as it looks like this proposal has been adopted (see `community.okd`), should we close this issue, and also the other `topic/openshift` labeled issues, and propose moving them to the `community.okd` repo?

Additionally, we would need a follow-up issue: Remove the current `integration` tests since they are only running on a severely outdated openshift 3.9 instance set up by `ansible-test` (remove `tests/integration/targets/kubernetes`, and the CI workflow job for integration tests—or maybe figure out a way to still have some limited coverage so the codecov bot can work? That could be part of the follow-up.

Also related to that follow-up: https://github.com/ansible/ansible/issues/71383

**Comment by tima** [comment]
Agreed @geerlingguy. We're moving ahead with this proposal so it can be closed. 

Will file an issue to discontinue running the openshift CI tests here. I've been meaning to go through the topic/openshift labeled issues. I suspect one or two may not be relevant in OCP4.
