### ISSUE TITLE
Return helm values even if check_mode is active

### ISSUE THREAD

**Issue by Geethree** [ansible-collections/community.kubernetes#188]
##### SUMMARY
Currently the helm `values` are only returned if check_mode is not active.

https://github.com/ansible-collections/community.kubernetes/blob/666b75eba4d11e4d20b25df74b07acfe8cf7a593/plugins/modules/helm.py#L482-L488

Vs.

https://github.com/ansible-collections/community.kubernetes/blob/666b75eba4d11e4d20b25df74b07acfe8cf7a593/plugins/modules/helm.py#L500-L506

When it comes to constructing some CD pipelines via ansible, it is often useful - to me at least - to determine if ansible _will_ change anything when running the playbook (check_mode), and report those changes.. somewhere (like a PR!).

Unfortunately, this is not possible via this module as it currently stands. Though it appears that it could easily return the values with a few lines of code. 

Would this feature be useful to the community? Happy to fork and PR if so. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`helm`

**Comment by Akasurde** [comment]
@Geethree Definitely, you can go ahead and create PR for this. Thanks.

**Comment by tima** [comment]
Sounds good to me @Geethree.

**Comment by tima** [comment]
Closed by #192
