### ISSUE TITLE
Using a lookup in k8s module 'src' results in Python crashing on macOS

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/community.kubernetes#205]
##### SUMMARY

This is a fun one: sometimes I want to download a manifest from an HTTP endpoint and deploy it into the cluster. When I do this passing it in as `src` or `definition`, instead of giving any helpful error, it ends up crashing Python on macOS:

```
objc[19036]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[19036]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
ERROR! A worker was found in a dead state
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

k8s

##### ANSIBLE VERSION

```paste below
2.9.12
```

##### OS / ENVIRONMENT

macOS 10.15.6

##### STEPS TO REPRODUCE

```yaml
- name: Deploy cert-manager into the cluster (required for Go operator).
  k8s:
    state: present
    src: "{{ lookup('url', 'https://github.com/jetstack/cert-manager/releases/download/v0.16.1/cert-manager.yaml') }}"
```

(Same thing didn't work with `definition` instead of `src`.)

##### EXPECTED RESULTS

I should get some sort of helpful error message (or should this even work?).

##### ACTUAL RESULTS

```paste below
TASK [Deploy cert-manager into the cluster (required for Go operator).] ********
objc[17641]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[17641]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
ERROR! A worker was found in a dead state
```

**Comment by Akasurde** [comment]
@geerlingguy This is a known issue - https://github.com/ansible/ansible/issues/49207. This is due to macOS security model.

**Comment by tima** [comment]
@geerlingguy and @Akasurde this sounds like a "wontfix." Is this worth documenting?

**Comment by Akasurde** [comment]
@tima I think, Ansible main documentation is the proper location for this because this affects all lookup plugin.
