### ISSUE TITLE
Refactor: Split up perform_action method in module_utils

### ISSUE THREAD

**Issue by tima** [ansible-collections/community.kubernetes#220]
Derived from feedback from @fabianvf:

The [`perform_action` method in module_utils/raw.py](https://github.com/ansible-collections/community.kubernetes/blob/main/plugins/module_utils/raw.py#L235) should be refactored into more independent focused bits that make it easier for collection like community.okd to override specific behaviors when needed.

As part of this work, other methods in `raw.py` should be reviewed and identified in a separate issue for further refactoring.

**Comment by Akasurde** [comment]
resolved_by_pr #231
