### ISSUE TITLE
List the rbac permissions required for each module

### ISSUE THREAD

**Issue by servo1x** [ansible-collections/community.kubernetes#238]
##### SUMMARY
It is unclear what RBAC permissions are required for each module.

##### ISSUE TYPE
- Documentation Report

**Comment by geerlingguy** [comment]
@servo1x - These modules just use Kubernetes' API to interact with a cluster. The RBAC permissions for any given resource would be documented within the Kubernetes installation itself.

These modules just require some form of authentication/authorization, usually in the form of a kubeconfig file, and then whatever you can do with that and something like `kubectl`, these modules can also do.

There isn't anything in particular these modules could document regarding RBAC that I can think of.
