### ISSUE TITLE
Remove the k8s_auth module (and other bits moved to okd collection)

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/community.kubernetes#240]
##### SUMMARY

We moved the k8s_auth module to openshift_auth in the `community.okd` collection in this issue: https://github.com/ansible-collections/community.okd/pull/33

We need to now remove the k8s_auth module (and any supporting code/docs) from this collection, but this should be reserved until the 2.0 release of this collection since it is a breaking change.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

k8s_auth

##### ADDITIONAL INFORMATION

N/A

**Comment by Akasurde** [comment]
resolved_by_pr #376
