### ISSUE TITLE
Add to new template parameter test case - template file with multiple resource definitions

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/community.kubernetes#243]
##### SUMMARY

After https://github.com/ansible-collections/community.kubernetes/pull/230 was merged, I wondered if multiple YAML documents, e.g.:

```yaml
---
resource_one_here:

---
resource_two_here:
```

Would be parsed and applied correctly, without the additional use of something like `from_yaml_all` in the `definition` parameter.

Maybe to make sure this behavior continues working in the future (assuming it works now), we could include _two_ resources in one of the j2 files, e.g. add a Service to the `molecule/default/templates/pod_template_two.j2` file.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

k8s / template

##### ADDITIONAL INFORMATION

N/A

**Comment by geerlingguy** [comment]
cc @tima, @Akasurde

**Comment by Akasurde** [comment]
resolved_by_pr #245
