### ISSUE TITLE
downstream build script creates a nonsensical sentence in the README

### ISSUE THREAD

**Issue by tima** [ansible-collections/community.kubernetes#262]
##### SUMMARY

The downstream build script replaces all occurrences of community.kubernetes with kubernetes.core, but it creates this nonsensical sentence in the README: "This repo hosts the kubernetes.core (a.k.a. kubernetes.core) Ansible Collection."

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

README (kubernetes.core)

##### ADDITIONAL INFORMATION

https://galaxy.ansible.com/kubernetes/core

**Comment by geerlingguy** [comment]
I mean, it's not _wrong_, it is also known as the same thing it's known as. But it is a rather silly line.

**Comment by tima** [comment]
Hence nonsencial. I've added low priority just for you @geerlingguy. ;)
