### ISSUE TITLE
Create kubernetes.core repository 

### ISSUE THREAD

**Issue by tima** [ansible-collections/community.kubernetes#265]
In preparing for #221, a new kubernetes.core repo needs to be created. Since both of these will need to exist for a time simultaneously this new repo will *not* be a clone or fork of this repo. For the moment, it will be a new repo and should include a README explaining the name change and migration. This will also fix the 404 error on the kubernetes.core collection Galaxy page repo link.

https://galaxy.ansible.com/kubernetes/core

**Comment by gundalow** [comment]
Created https://github.com/ansible-collections/kubernetes.core with the same owners as `community.kubernetes`

**Comment by gundalow** [comment]
Please accept the invite to the repo via https://github.com/ansible-collections/kubernetes.core/invitations

**Comment by tima** [comment]
Thanks @gundalow.
