### ISSUE TITLE
I'd like to help out with writing tests. Is there a specific area that tests would be wanted/needed?

### ISSUE THREAD

**Issue by cynthia-rempel** [ansible-collections/community.kubernetes#271]
Thanks for all your help!

**Comment by geerlingguy** [comment]
Thanks for asking! Currently we are good for tests in this collection, as we have been pretty diligent about adding adequate test coverage for every new feature in it, but I would suggest helping where you can in some of the other collections which are more lacking in coverage.

**Comment by cynthia-rempel** [comment]
Since you're the one who referred me here, and now are saying there's no need, I'm feeling like my help wasn't wanted in the first place.  Since I was directed to kubernetes.core at the contributor's summit, I reported the lack of interest in their repo.  I feel the right thing to do would have been to tell me no help was needed at the other repo.

**Comment by geerlingguy** [comment]
@cynthia-rempel - In the other issue, I meant that this is  the repository where active development is happening for the Kubernetes Collection (though that will change at some point in the next month, as we move to the `kubernetes.core` repository).

I know there are some collections in the https://github.com/ansible-collections organization that may need assistance with increasing test coverage, but currently the Kubernetes collection is doing okay on that front (at least in my opinion—I'd be happy to hear different from other maintainers). It is not at all that your help is not wanted, it is more that I'm not sure what I would be able to point you to in this repository in particular.

Thank you for understanding, it is sometimes hard to convey what is meant just through text online.

**Comment by cynthia-rempel** [comment]
Thanks for taking the time to clarify this!  I really appreciate it :)
