### ISSUE TITLE
Support for helm package management

### ISSUE THREAD

**Issue by tima** [ansible-collections/community.kubernetes#28]
##### SUMMARY

This collection should include a module for Helm package management.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

helm and/or helm_cli

##### ADDITIONAL INFORMATION

Helm is the Kubernetes package manager and maintained by the CNCF. While not every Kubernetes tool belongs in this one collection, Helm is too vital not to be included. It should be a core part of any Ansible Kubernetes collection given its status in the ecosystem and the common use of Ansible to deploy, upgrade, manage and remove applications of any type.

The existing helm module in Ansible core is insufficient in that it uses special python libraries that emulate helm instead of wrapping the helm tool itself. It also currently only supports Helm2 while the ecosystem has quickly moved to Helm3. There are many other [known outstanding issues](https://github.com/ansible/ansible/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+helm).

I propose we instead consider this implementation that utilizes the actual Helm CLI for better compatibility and reliability over time:  https://github.com/ansible/ansible/pull/62450

**Comment by geerlingguy** [comment]
I think a Helm module would fit in this collection nicely, as it is a tool that is exclusively used with Kubernetes, and as you mention, it is a fairly standard tool used in many deployments.

I've commented in the other PR in ansible/ansible and asked if the author would be willing to submit a PR against _this_ repository.

**Comment by tima** [comment]
Also to your point @geerlingguy and looking at it another way -- what collection would a helm module go otherwise? I don't see there being more than one module really ever. Maybe a module_util or some supporting code gets identified? To me it would seem silly to create and maintain a collection with so little content just because helm != k8s.

**Comment by geerlingguy** [comment]
Merged helm modules via https://github.com/ansible-collections/community.kubernetes/pull/61 — this issue can be closed 🥳
