### ISSUE TITLE
No module named google.auth

### ISSUE THREAD

**Issue by nergalex** [ansible-collections/community.kubernetes#284]
##### SUMMARY
**CONTEXT**
first install and play with `community.kubernetes collection`. It doesn't work before. (see attached playbook `get_test.yaml`)

**SYMPTOM**
job output `No module named google.auth` (see attached file job_24196_output.txt)

**WORKAROUND**
add `__init__.py` in package `google`. File copied from `https://raw.githubusercontent.com/googleapis/google-auth-library-python/master/google/__init__.py`
[job_24196_output.txt](https://github.com/ansible-collections/community.kubernetes/files/5438093/job_24196_output.txt)
[get_test.yaml.TXT](https://github.com/ansible-collections/community.kubernetes/files/5438094/get_test.yaml.TXT)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.kubernetes.k8s_info

##### ANSIBLE VERSION

```
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/cyber/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 20 2020, 17:08:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
Tower 3.7.3

##### OS / ENVIRONMENT
```
Red Hat Enterprise Linux Server release 7.9 (Maipo)
```

##### STEPS TO REPRODUCE
create custom env
```
$ sudo virtualenv /opt/custom-envs/cloudbuilder-collection
$ source /opt/custom-envs/cloudbuilder-collection/bin/activate
$ pip install psutil openshift
$ deactivate
```
Play get_test.yaml with collection community.kubernetes 1.1.1 in requirements

##### EXPECTED RESULTS
With workaround: OK, it works.

##### ACTUAL RESULTS
See job_24196_output.txt

**Comment by geerlingguy** [comment]
It looks like the primary issue is the openshift  Python library is not installed on the machine where the playbook runs. It should be installed with `pip install openshift`

**Comment by nergalex** [comment]
`openshift` package is well installed but during module import, `google `package is not found. In `detailed_job_output.txt`, you will find the detailed error:
```
      File \"/opt/custom-envs/cloudbuilder-collection/lib/python2.7/site-packages/kubernetes/config/kube_config.py\", line 29, in <module>
        from google import auth
        ImportError: No module named google
```
[detailed_job_output.txt](https://github.com/ansible-collections/community.kubernetes/files/5441688/detailed_job_output.txt)

**Comment by tima** [comment]
@nergalex Understood, but all of the things you are reporting -- Ansible Tower custom environment and the installation of the python openshift client library -- are outside of the scope of this project. Have you contacted Red Hat support on this?

**Comment by nergalex** [comment]
OK I will
Thank you for your answer
