### ISSUE TITLE
Support for `--skip-crds` with helm v3 cli

### ISSUE THREAD

**Issue by stephenmoloney** [ansible-collections/community.kubernetes#296]
### SUMMARY
Support for `--skip-crds` with helm v3 cli

##### ISSUE TYPE
Support for `--skip-crds` with helm v3 cli

##### COMPONENT NAME
helm

##### ADDITIONAL INFORMATION
This is sometimes desired behaviour or required behaviour

**Comment by tima** [comment]
@stephenmoloney Thanks for filing this. Could you expand your description on the uses cases for this feature? Why and when would you use this. Why is this important. Things that "sell" the idea for inclusion in a future release.

**Comment by stephenmoloney** [comment]
@tima 
Sure. But essentially the reason for inclusion of `--skip-crds` will be the same reason as helm cli includes it.
Give me some time and I will document this

The tricky part will be the difference in behavior and how this is achieved between helm v3 and helm v2.
How is the ansible module going to handle differences between them.

Does it try to abstract those differences away and support on both versions - that will make this a bit problematic.

**Comment by tima** [comment]
@stephenmoloney The `helm` modules in here only support Helm3. We have no intention of supporting Helm2. There is a deprecated `helm` module that kind of does that. (It's based on a python library that wasn't keeping up with helm2 and went unmaintained.)

**Comment by stephenmoloney** [comment]
Ok @tima 

That is a good thing.

Then I definitely think `--skip-crds` should be supported in the same way as arguments like `atomic` and `wait-timeout` are.

**Comment by Akasurde** [comment]
@stephenmoloney Are you working on the PR? Let me know.

**Comment by stephenmoloney** [comment]
Gimme a bit of time. I will let you know within 1 month.

**Comment by stephenmoloney** [comment]
@Akasurde I won't be able to get to this soon I'm afraid.
