### ISSUE TITLE
Two new CI failures in sanity and molecule tests

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/community.kubernetes#323]
##### SUMMARY

We are now hitting two new errors in CI causing failed builds: https://github.com/ansible-collections/community.kubernetes/actions/runs/405144301

First, in the sanity test:

```
ERROR: Found 3 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/k8s.py:0:0: doc-default-does-not-match-spec: Argument 'append_hash' in argument_spec defines default as (False) but documentation defines default as (None)
ERROR: plugins/modules/k8s.py:0:0: doc-default-does-not-match-spec: Argument 'apply' in argument_spec defines default as (False) but documentation defines default as (None)
ERROR: plugins/modules/k8s_service.py:0:0: doc-default-does-not-match-spec: Argument 'apply' in argument_spec defines default as (False) but documentation defines default as (None)
```

Second, in the molecule test:

```
  Warning: : running playbook inside collection community.kubernetes
  Warning: :  * Failed to parse
  /home/runner/.cache/molecule/kubernetes/default/inventory/ansible_inventory.yml
  with ansible_collections.community.kubernetes.plugins.inventory.k8s plugin:
  Incorrect plugin name in file: none found
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

CI

**Comment by Akasurde** [comment]
- Sanity checks resolved in https://github.com/ansible-collections/community.kubernetes/pull/325
- I'm still investigating the molecule issue
- Found another issue in molecule test - https://github.com/ansible-collections/community.kubernetes/pull/326

**Comment by geerlingguy** [comment]
@Akasurde - All right, looks like those PRs have fixed up all the current failures, and I'm seeing passing tests now, so I am happy to close this out now :)
