### ISSUE TITLE
community.kubernetes.helm support values in template j2 file

### ISSUE THREAD

**Issue by PengBAI** [ansible-collections/community.kubernetes#338]
##### SUMMARY

add new parameter like values_template to support j2 template file.
Or 
update the existing parameter values_files to support j2 file

```
  - name: "Install or update gitlab-runner chart if existing"
    community.kubernetes.helm:
      name: "chart-{{ item.offer_name }}"
      chart_ref: "{{ helm_repo_name }}/{{ chart_name }}"
      chart_version: "{{ chart_version }}"
      release_namespace: "{{ namespace_name }}"
      values_template :
        - "my-values.yml.j2"
```

##### ISSUE TYPE
- Feature Idea

**Comment by goneri** [comment]
Hi @PengBAI,

If I understand properly, this change is actually not required. You can already use the `template` module to prepare a "values file" and in a second step, pass the result file to `helm` through its `values_files` key.

If you think we misunderstood something, feel free to reopen the issue.
