### ISSUE TITLE
Remove module inheritance

### ISSUE THREAD

**Issue by fabianvf** [ansible-collections/community.kubernetes#36]
##### SUMMARY

Currently we have the [`KubernetesAnsibleModule`](https://github.com/ansible-collections/kubernetes/blob/master/plugins/module_utils/common.py#L267) and [`KubernetesRawModule`](https://github.com/ansible-collections/kubernetes/blob/master/plugins/module_utils/raw.py#L65) that most of our modules inherit from, but this is a bad pattern and has already bitten us with the `k8s_scale` module. We have an [`AnsibleMixin`](https://github.com/ansible-collections/kubernetes/blob/master/plugins/module_utils/common.py#L147) that works fine, though we should remove the argspec from it.

The main reason this pattern is harmful is that parameters are shared across modules, and adding or changing arguments in one will passively propagate to subclasses of that module. `k8s_scale` for example, inherits parameters from `k8s`, and has broken in the past when we added arguments to the `k8s` module ([issue here](https://github.com/ansible/ansible/issues/59021)). Each module should own the arguments it accepts, and code sharing should be limited to shared utilities rather than module definitions.

##### ISSUE TYPE
- Technical Debt

**Comment by tima** [comment]
The `k8s_scale` module is a good example of a module that needs work to untangle the code.
