### ISSUE TITLE
Support of binary_path for kubectl go binary

### ISSUE THREAD

**Issue by RafalSkolasinski** [ansible-collections/community.kubernetes#398]
##### SUMMARY

Helm modules allow to specify `binary_path` - see [docs](https://docs.ansible.com/ansible/2.10/collections/community/kubernetes/helm_module.html). 

It would be nice if one could also specify `kubectl` binary when using the main [community.kubernetes.k8s](https://docs.ansible.com/ansible/2.10/collections/community/kubernetes/k8s_module.html) module. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

community.kubernetes.k8s

##### ADDITIONAL INFORMATION

I want to make use of the `community.kubernetes.k8s` in the self-contained environment adding another `role` that will first fetch a desired version of `kubectl`, `helm`, etc. and then use these versions when calling the `community.kubernetes.k8s` modules. 

```yaml

```

**Comment by gravesm** [comment]
Hi @RafalSkolasinski, the helm modules and the k8s module function a bit differently. For the helm modules we call out to the helm binary, but the k8s module uses the python kubernetes client, not kubectl to interact with kubernetes.

**Comment by RafalSkolasinski** [comment]
Hi @gravesm, okay, great, so basically there is no dependency on the `kubectl` binary being present on the host system? 
That is even better news :)

**Comment by gravesm** [comment]
That's correct. The one caveat is that if you are using the k8s inventory plugin or the kubectl connection plugin they will require that kubectl is present.
