### ISSUE TITLE
Wrong examples in k8s module

### ISSUE THREAD

**Issue by seocam** [ansible-collections/community.kubernetes#408]
There is no template argument in the roof of module k8s as stated in the examples:

https://github.com/ansible-collections/community.kubernetes/blob/5fc3dd02bf19fd4d70d99278969d786100b18feb/plugins/modules/k8s.py#L185-L196

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
k8s module

**Comment by tima** [comment]
What version of the collection are you using? That param was added in v1.1.0.

**Comment by tima** [comment]
@seocam https://github.com/ansible-collections/community.kubernetes/blob/5fc3dd02bf19fd4d70d99278969d786100b18feb/plugins/modules/k8s.py#L306
