### ISSUE TITLE
k8s module should have some basic filtering power(JSON output)

### ISSUE THREAD

**Issue by uditgaurav** [ansible-collections/community.kubernetes#50]
**SUMMARY**

While using `k8s_info` modules we get the output in JSON format in the `register` variable then we have to add an extra task (can be a `set_fact` ) to filter the useful values. Can/ Do we have `k8s_info` modules with some basic filtering power so that we don't need to add an extra task for getting one value inside our JSON output?

**ISSUE TYPE**

- Feature Idea

**COMPONENT NAME**

MODULE NAMES

- `K8s`
- `k8s_info` / `k8s_facts`(before ansible 2.9)

**ADDITIONAL INFORMATION**

I'm just correlating these tasks with shell commands
We do `-o jsonpath={.metadata.name}` to filter name (for example) how to filter this or any other component using the `k8s` Ansible module?

**Comment by geerlingguy** [comment]
Just noting that I've seen _some_ people use the [`json_query`](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#json-query-filter) filter, but that depends on a possibly-unmaintained library, jmespath.

I don't know if we'd want to pre-process and re-arrange the output in the module itself, as it would add a lot of complexity and is not really the pattern used in other modules either... afaict. But I'd rather others chime in here.

**Comment by jamescassell** [comment]
It ships in RHEL 8, and it's very common in playbook and roles from what I've seen. Would you recommend a new jq-based filter?

**Comment by tima** [comment]
Thanks for this suggestion. This is something better served by the ansible core on the whole than a K8s collection specific solution. The `json-query` filter exists and has been used for this function, but has maintenance issues. A `jq` filter as @jamescassell suggests would be ideal in community.general or the core.
