### ISSUE TITLE
kubectl package installer role via OS package managers

### ISSUE THREAD

**Issue by ericsysmin** [ansible-collections/community.kubernetes#82]
##### SUMMARY
Allow a role community.kubernetes.kubectl to install the kubectl requirement for these modules.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.kubernetes.kubectl

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by Akasurde** [comment]
@ericsysmin Thanks for this feature request. Would you be interested in adding roles like `kubectl_installer` under `roles` directory? Let me know.

Thanks,

**Comment by ericsysmin** [comment]
Sure, I can do that. Sorry for the delayed response, I was away on vacation.

**Comment by alinabuzachis** [comment]
Hello @ericsysmin, by policy we don't push any role in this collection. Can you please use galaxy to publish it?
