### ISSUE TITLE
Invalid kube-config file. No Configurations found

### ISSUE THREAD

**Issue by ShubhamGundawarIBM** [ansible-collections/community.kubernetes#90]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
 I am using the K8s module of Ansible to run a role

##### ANSIBLE VERSION

```
ansible 2.9.6

```

##### CONFIGURATION

```
NO output

```

##### OS / ENVIRONMENT
```Red Hat Enterprise Linux Server release 7.8 (Maipo)```

##### STEPS TO REPRODUCE

I am running a role in ansible which is using the k8s module, When I try to run the playbook I get this error

```- name: Create a Service object by reading the definition from a file
  k8s_raw:
    state: present
    definition: /home/DevOps/kubedeploy/deployment.yaml


```

##### EXPECTED RESULTS

The ansible should create a namespace, from the script provided above

##### ACTUAL RESULTS

Error when coming to the step of creating the namespace

```
"module_stderr": "OpenSSH_8.1p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 47: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 9.199.148.69 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 9229\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to 9.199.148.69 closed.\r\n",
    "module_stdout": "/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory\r\nTraceback (most recent call last):\r\n  File \"/home/devops/.ansible/tmp/ansible-tmp-1589257948.744666-75842198948934/AnsiballZ__k8s_raw.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/devops/.ansible/tmp/ansible-tmp-1589257948.744666-75842198948934/AnsiballZ__k8s_raw.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/devops/.ansible/tmp/ansible-tmp-1589257948.744666-75842198948934/AnsiballZ__k8s_raw.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.clustering.k8s._k8s_raw', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_k8s_raw_payload_6tbq3G/ansible_k8s_raw_payload.zip/ansible/modules/clustering/k8s/_k8s_raw.py\", line 279, in <module>\r\n  File \"/tmp/ansible_k8s_raw_payload_6tbq3G/ansible_k8s_raw_payload.zip/ansible/modules/clustering/k8s/_k8s_raw.py\", line 275, in main\r\n  File \"/tmp/ansible_k8s_raw_payload_6tbq3G/ansible_k8s_raw_payload.zip/ansible/module_utils/k8s/raw.py\", line 171, in execute_module\r\n  File \"/tmp/ansible_k8s_raw_payload_6tbq3G/ansible_k8s_raw_payload.zip/ansible/module_utils/k8s/common.py\", line 188, in get_api_client\r\n  File \"/root/.local/lib/python2.7/site-packages/kubernetes/config/kube_config.py\", line 739, in load_kube_config\r\n    persist_config=persist_config)\r\n  File \"/root/.local/lib/python2.7/site-packages/kubernetes/config/kube_config.py\", line 701, in _get_kube_config_loader_for_yaml_file\r\n    'Invalid kube-config file. '\r\nkubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by tima** [comment]
@ShubhamGundawarIBM You're not using the `k8s` module (as it works today) correctly.

[The 'definition' param takes a data structure like a dict or list, not a file name](https://docs.ansible.com/ansible/latest/modules/k8s_module.html#parameter-resource_definition). In order to read in a file you'd have to do something like this: 

`definition: "{{ lookup('template','/home/DevOps/kubedeploy/deployment.yaml') | from_yaml }}`

I'm assuming you are using some sort of variable replacement or other logic in your file so I'm using 'template'. If the file is completely static you could use the file lookup function.

[There is a feature request planned to add reading a template without the all the extra `lookup` syntax](https://github.com/ansible-collections/community.kubernetes/issues/37) to the `k8s` module, but that is not here today. When that gets implemented you would be able to do what you attempted.

**Comment by ShubhamGundawarIBM** [comment]
Hey tima,

```
- name: Create a k8s namespace
  k8s:
    name: test
    api_version: v1
    kind: Namespace
    state: present
```
Even After running this role, The error remains the same.

**Comment by tima** [comment]
@ShubhamGundawarIBM 

From the error message you posted before:

> 'Invalid kube-config file. '\r\nkubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.\r\n",

What kube-config params are you feeding the task to access your cluster?

**Comment by ShubhamGundawarIBM** [comment]
@tima 
I have not passed any params in the Kube-config file, The file is currently empty.

**Comment by ShubhamGundawarIBM** [comment]
@tima 
I am using microk8s, And have a single node cluster, I am running my ansible script from MAC, and my target machine is RHEL. Kubernetes was installed by micok8s, I did not configure anything after installation, Kubectl works fine

**Comment by tima** [comment]
My guess is that works for you because microk8s sets you up with a kube-config file to your local cluster and maybe some pathing so kubectl can find on your local environment. (Do you have something like a ~/.kube/config?) Without going too deep, Ansible won't be able to see your local setup. (It's a good idea not to rely on the local environments configuration and be more explicit.) So if you don't provide a kube-config file or equivalent params, your playbook has no idea which cluster to talk to and how to authenticate.

**Comment by ShubhamGundawarIBM** [comment]
Yes I do have ~/.kube/config file with it is empty.

**Comment by alexkunin** [comment]
I had similar issue with `k3s`, it installs own `kubectl` which is aware of special config file placement, but `k8s` module was not able to find it. Adding environment variable `KUBECONFIG` helped:

```yaml
- hosts: all
  roles:
    - name: xanmanning.k3s
      become: true
      k3s_write_kubeconfig_mode: 644
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
```

Relevant part starts from `environment:`, but you probably need to specify different variable value for `microk8s`.

**Comment by ShubhamGundawarIBM** [comment]
@alexkunin 
Where can I find the path of microk8s kube config file

**Comment by ShubhamGundawarIBM** [comment]
@alexkunin 
So mentioning kubeconfig: inside my role did the trick.
Great Thanks
